### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by Nackenkelle** [man4red/PsBlackwakeMonitor#1]
Validating server at "D:\Server\Blackwake\blackwake_server\"...Ausnahme beim Aufrufen von "Start" mit 0 Argument(en):  "Das System kann die angegebene Datei nicht finden"
In D:\Server\Blackwake\blackwake_server\PsBlackwakeMonitor.ps1:303 Zeichen:3
+         $p.Start() | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

Ausnahme beim Aufrufen von "WaitForExit" mit 0 Argument(en):  "Diesem Objekt ist kein Prozess zugeordnet."
In D:\Server\Blackwake\blackwake_server\PsBlackwakeMonitor.ps1:304 Zeichen:3
+         $p.WaitForExit()
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In D:\Server\Blackwake\blackwake_server\PsBlackwakeMonitor.ps1:305 Zeichen:3
+         $stdout = $p.StandardOutput.ReadToEnd()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In D:\Server\Blackwake\blackwake_server\PsBlackwakeMonitor.ps1:306 Zeichen:3
+         $stderr = $p.StandardError.ReadToEnd()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by man4red** [comment]
@Nackenkelle thx for report!
It would be nice if you provide info in English.
For now it seems that Powershell is unable to create object ```New-Object System.Diagnostics.Process```
Also check that this path is correct ```$global:steamCMD = "C:\SteamCMD\steamcmd.exe"```
What version of Powershell do you use?
Please provide output of ```$PSVersionTable```
